services:
  faqapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "5134:8080"
      # - "8888:8888"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - DOTNET_ENVIRONMENT=Development
    working_dir: /workspace/src
    tty: true

  faqapp_db:
    container_name: faqapp-db
    image: mysql:8.4
    restart: always
    ports: 
      - "33066:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: faqapp
      MYSQL_PASSWORD: faqapp
      MYSQL_DATABASE: app

volumes:
  mysql_data:
